CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(15) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" varchar(15) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rol" varchar(15) NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(15) NOT NULL,
  "last_name" varchar(15),
  "age" int,
  "email" varchar(25) UNIQUE NOT NULL,
  "password" varchar(15) NOT NULL
);

CREATE TABLE "users_rol" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int NOT NULL,
  "rol" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(40) UNIQUE NOT NULL,
  "description" text,
  "level" int,
  "teacher" int NOT NULL,
  "category" int
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course" int UNIQUE NOT NULL,
  "url" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "purchased_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" int NOT NULL,
  "course" int NOT NULL
);


/* CREACION DE RELACIONES FK*/

ALTER TABLE "users_rol" ADD FOREIGN KEY ("rol") REFERENCES "roles" ("id");

ALTER TABLE "users_rol" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "courses_video" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");

ALTER TABLE "purchased_courses" ADD FOREIGN KEY ("user") REFERENCES "users" ("id");

ALTER TABLE "purchased_courses" ADD FOREIGN KEY ("course") REFERENCES "courses" ("id");


/*INGRESO DE REGISTROS*/

INSERT INTO level (level) VALUES ('basico'), ('intermedio'), ('avanzado');

INSERT INTO roles (rol) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO categories (category) VALUES ('diseño UI/UX'), ('programacion'), ('cybersecurity');

INSERT INTO users (first_name, last_name, age, email, password) VALUES
 ('marco', 'cardenas', '39', 'marco@gmail.com', '39'),
 ('maria', 'araujo', '32', 'maria@gmail.com', '456'),
 ('fernando', 'colunga', '45', 'fernando@gmail.com', '111'),
 

INSERT INTO users_rol VALUES
 (1, 1, 1),
 (2, 2, 1),
 (3, 3, 1),


INSERT INTO courses (title, description, level, teacher, category) VALUES
('programacion 1', 'programacion OO', 1, 5, 2),
('programacion fullstack', 'programacion en varios lenguajes', 3, 6, 2),
('html5', 'crea tu primera pagina web', 2, 7, 2),


INSERT INTO courses_video (course, url) VALUES
(1, 'https://programacion.com'),
(2, 'https://rubyonrails.com'),
(3, 'https://html.com'),
(4, 'https://photoshop.com'),

INSERT INTO purchased_courses VALUES
(1, 1, 1),
(2, 1, 6),
(3, 2, 2),
